# Generated by Django 6.1.1 on 2026-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(choices=[('consolas', 'Consolas de Videojuegos'), ('notebooks', 'Notebooks y Computadores'), ('componentes', 'Componentes de Hardware'), ('perifericos', 'Periféricos y Accesorios')], default='consolas', max_length=50, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio (CLP)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('descripcion', models.TextField(verbose_name='Descripción técnica')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Disponible para venta?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
